### ISSUE TITLE
Notebooks in Rust

### ISSUE THREAD

**Issue by rgbkrk** [Carreau/ipynb-rs#1]
Hey Matthias!

Over the weekend I put together an [`nbformat` crate](https://github.com/runtimed/runtimed/tree/main/crates/nbformat) for use in Zed (first used in https://github.com/zed-industries/zed/pull/19756). You might also be interested in `runtimelib` and `jupyter-serde`.

Demo of it in action:

https://github.com/user-attachments/assets/f5519a32-2c31-48d7-adb4-0414533b51b4

**Comment by Carreau** [comment]
Sweet ! It's good to hear from you; I have not touched rust in a long time, but maybe it's a good occasion to restart !

**Comment by Carreau** [comment]
Hey, do you want ownership of ipynb crate ?

**Comment by rgbkrk** [comment]
I don't necessarily need it, though I'm happy to use it if a good case comes up. I mostly popped by to say hello so you could hear about some of the rust bindings (I haven't really broadcast it anywhere other than integrating them directly into https://github.com/denoland/deno and https://github.com/zed-industries/zed/). We should do a zoom call sometime!
